---
- name: Install and configure Wazuh Agent
  hosts: test
  become: yes
  tasks:
    - name: Add Wazuh repository GPG key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Wazuh agent
      apt:
        name: wazuh-agent
        state: present

    - name: Configure Wazuh agent
      copy:
        content: |
          <ossec_config>
            <client>
              <server>
                <address>106.51.39.244</address>
                <port>1514</port>
                <protocol>udp</protocol>
              </server>
            </client>
          </ossec_config>
        dest: /var/ossec/etc/ossec.conf
        owner: root
        mode: '0640'
      notify:
        - restart wazuh-agent

  handlers:
    - name: restart wazuh-agent
      systemd:
        name: wazuh-agent
        state: restarted
